import React from 'react';
import "./Varanasi.css";
// import Money_converter from './Money_converter';
import Page from './Page';

const Varanasi = () => {


  return(
    <div>
      <div className="map">
        <img src="https://www.worldatlas.com/img/locator/city/054/9054-varanasi-locator-map.jpg" alt=""/> <br />
        <a target="_blank" href="https://www.google.com/maps/place/Varanasi">View more</a>
      </div>
      <div className="title">
      <img src="https://images.pexels.com/photos/1260801/pexels-photo-1260801.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="" />
      <h3>Voyage - l'Inde </h3>
      <h1>VARANASI</h1>
      </div>
      <div>
        <p>J’ai passé une petite semaine à Varanasi alias Bénarès de son nom colonial, la ville sacrée où les hindous viennent brûler leurs morts et ainsi mettre fin au cycle des réincarnations. C’est une des plus vieilles villes du monde parait-il.</p>

        <p>La ville de Varanasi est surtout célèbre pour ses ghâts, berges recouvertes de marches de pierres qui permettent aux dévots hindous de descendre au fleuve pour y pratiquer ablutions et pujas (offices religieuses). Le bain dans le Gange est censé laver de tous les péchés. C’est aussi sur des ghâts spécialisés, le plus fameux étant Manikarnika, que l’on pratique les crémations à Bénarès. (Wikipedia)</p>

        <p>Impression à chaud : émerveillement, excitation, extase. Licornes multicolores et ratatouilles de mémé.</p>

        <p>Impression après plus de 4 mois en Inde et 8 mois de voyage : c’est une belle ville pour attrape couillons.</p>

        <p>Bon il faut rappeler que je suis arrivée durant Diwali, une fête religieuse très importante, la ville était bondée, les gens magnifiquement parés et le spectacle était incroyablement beau. C’était donc un moment spécial qui teintait la ville d’une majestueuse nuance de sacré. La mise en scène était encore plus travaillée que d’habitude. J’avais également la tête bourrée de mysticisme indien, que je voyais alors un peu comme l’ENS d’ULM : un truc puissant et vénéré mais aux mécanismes pas bien clairs. J’étais très impressionnée par la vue du Gange, qu’on m’avait présenté comme plus qu’une rivière, comme une déité. Je payais donc tout mon respect aux eaux sales et indolentes. De plus j’ai passée la semaine en compagnie du local qui m’a hébergé lors du fiasco de mon arrivée, j’ai donc eu un aperçu direct et authentique de la vie locale, en ville et à la campagne, car il m’a emmené sur sa moto voir ses belles sœurs un jour, des paysannes vivant de l’autre côté du Gange.</p>

        <p>Mais j’étais d’une naïveté abyssale. Tout le monde il est gentil, tout le monde il est beau a été mon refrain pendant le premier mois de mon périple indien. Malgré les évidences, malgré les mises en garde des Aurovilliens.</p>

        <p>Ensuite, après la rencontre d’Ori, je suis passée à un discours moins innocent mais toujours assez inconscient.</p>

        <p>Après une césure qui m’a permis de décanter mes émotions de mes idées et un retour en Inde qui m’a permis d’observer de nouveau avec un regard plus avisé et acéré, je me marre et suis en même temps nostalgique de cette première rencontre fusionnelle, enthousiaste, généreuse, barbouillée d’une jolie sottise béate et sans distance.</p>

        <p>Pendant ma semaine à Varanasi, j’ai donc beaucoup marché, à la découverte des petites ruelles du Chowk, l’ancien quartier, qui m’ont laissées une impression indélébile. On se faufile dans un labyrinthe infini de petites ruelles pavées qui ne font pas plus d’une largeur d’épaule, bordées par moultes échoppes, restaurants, chai sellers, guest houses, se frayant un chemin entre les vaches colossales et les chiens fourbes. Le Chowk est tout contre les Ghats, les escaliers qui descendent jusqu’au Gange. On se perd donc délicieusement dans cette succession de dédales qui nous ramènent toujours aux magnifiques volées de marches qui s’enfoncent dans l’eau immobile. La ville recèle de trésors cachés ou en cours de destruction : je ne sais plus pourquoi ils sont en train de reconstruire les rues qui mènent à la Ghat principale, celle qui sert à la crémation des morts, et de détruire de multiples temples sur leur chemin. La vue de la crémation des morts m’a fait beaucoup d’effet évidemment, voir le prochain article à ce sujet. J’en ai également profité pour visiter le reste de la ville, à l’arborescence énorme, toujours secouée d’une agitation frénétique, et découvrir, émerveillée, les rues indiennes sales, puantes, croulantes de monde. J’ai également beaucoup discuté : de l’histoire des idées avec les deux Antho, français dreadeux très cool qui fumaient bidi sur bidi; des stalkers indiens avec Sophie, quadragénaire déjantée aux cheveux rouges, un peu perchée mais sacrément forte, qui passait sa journée à essayer d’échapper à son chauffeur très envahissant; du karma yoga et de l’instant présent avec Rohit, jeune indien atypique, très bavard et pas très stable mais intéressant et passionné.</p>

        <p>J’ai eu pas mal de galères là-bas, notamment quelques jours où il me fut impossible de retirer de l’argent car les distributeurs étaient à sec. En bonne débutante je suis également tombée dans tous les panneaux, même ceux qui affichaient clairement en sigles lumineux « escroquerie imminente ». Après 4 mois en Inde quand je me rappelle combien je payais ceci ou cela ça me met dans une rage vermoulue. Quelle débile. Pour ma défense, j’ai encore le souvenir dans ma chair de ce choc de la négociation indienne : expéditive, brutale, impitoyable. Il faut se battre comme un chien errant pour payer le juste prix, et Shiva sait qu’ils savent se battre. Puis quand on débarque fraîchement avec notre gueule d’emoji heureux on fait une proie facile. Donc je ne sais pas si Varanasi est spécialement dure en affaire ou si j’étais spécialement dure de la feuille mais il me semble tout de même ne pas avoir rencontrée une telle passion pour l’arnaque dans le reste de l’Inde. Le gros point négatif est la saleté et la puanteur de la ville, largement squattée par moultes bandes d’animaux qui se soulagent partout sans pudeur ou crachent à tout va des jets de pâan rougeâtres qui souillent le sol (ouais c’est un peu fort d’appeler les indiens des animaux mais je me suis faite cracher une fois dessus ce dégoûtant colorant et je peux vous dire que mon premier réflexe a été de chercher des yeux le lama crapuleux et non pas l’être humain mal élevé). L’autre point négatif largement répandu est l’arnaque mystique : la bande de faux sâdhu qui traînent sur les bords du Gange à fumer de l’herbe et soustraire des roupies à tous les touristes qui osent les prendre en photo. Il y a la masse d’imposteurs, soyez prévenus. Il m’est arrivée une drôle d’histoire avec le local qui m’a hébergé par la suite, un truc absolument inédit et surprenant de demande d’argent (tiens tiens) qui ne collait pas vraiment avec ses beaux discours d’alors sur notre amitié… bref vous l’aurez compris ouvrez-vous aux autres mais gardez bien fermé votre porte-monnaie.</p>

        <p>J’en profite pour faire une parenthèse sur ce fameux local. Il s’appelait Rony et avait dans les 27 ans si je me souviens bien. Il vivait avec toute sa famille (sa femme de 22 ans épousée par mariage arrangé, ses deux enfants en bas âge, ses parents, son frère et sa femme, leurs enfants, sa sœur enceinte et son mari) dans une masure qui ne comportait que quelques pièces : trois chambres avec des lits de bois, la cuisine intégrée à l’une d’elle, une pièce de béton avec un trou qui servait de toilette et salle de bain. Un gros bac d’eau douteuse pour douche. Des animaux plus ou moins sans-papiers squattaient la cuisine : différentes espèces d’oiseaux, différentes espèces de rats. J’ai passé le premier jour à essayer de m’intégrer avec les femmes, faire la cuisine. Mais comme elles ne parlaient pas anglais et n’étaient pas franchement amicales, ça a été plutôt un échec. J’ai cependant appris à faire des aloo paratha (sorte de galette fourrée à la patate), et goûté des drôles de mets locaux. J’ai surtout eu un bel aperçu de la condition moyenne des indiens des castes moyennes : aucune mesure d’hygiène, une vie répétitive à mourir et une évidente pauvreté, celle qui marque les corps. Ils étaient tous abîmés par la vie, bien qu’encore jeunes. Tous en surpoids plus ou moins sérieux. Rony avait les dents rongées et pourries par le pâan. Sa femme était malade (je n’ai pas tout compris) et sa sœur vivait une grossesse compliquée, mais les médicaments et l’hôpital coûtaient trop chers. Les femmes n’étaient pas éduquées, les hommes un peu plus, ils parlaient un anglais approximatif. Ils traînaient toute la journée dans la ville et buvaient pas mal le soir tandis que leurs femmes restaient enfermées à faire la cuisine. Après avoir abandonné la tentative d’intégration de la gente féminine, j’ai suivi Rony qui m’a trimballé dans toute la ville. Il parlait beaucoup du fait que les voyageurs étaient bienvenus et bénis des dieux, que notre amitié comptait beaucoup à ses yeux et qu’ils avaient plein d’amis chers à travers le monde qu’il avait rencontré au détour du chemin, comme moi. Bref un cœur pur dans un corps sain. Non, honnêtement, je nourrissais beaucoup de tendresse et de gratitude à son égard, mais il y a quelque chose que je n’ai fondamentalement pas saisi dans cette histoire. On trainait aussi beaucoup avec son meilleur ami, un brahmane (haute caste) avec qui j’ai eu l’occasion d’avoir une discussion assez intéressante sur la religion hindoue, l’amour, l’orientation sexuelle, le genre, la but de la vie, l’énergie.</p>

        <p>Ils me proposaient spontanément des cigarettes et des verres de whiskey dilués dans de l’eau le soir venu (façon traditionnelle de boire l’alcool fort en Inde). Moi j’acceptais tout, plus pour ne pas froisser que par réelle envie, et je me demande toujours si j’ai bien fait ou pas. Quel était donc le message implicite que je leur envoyais en acceptant ? Je suis pourtant persuadée – j’insiste – qu’ils étaient complètement bienveillants et absolument inoffensifs.</p>

        <p>J’ai passé de super moments avec eux et j’ai eu un rare accès à un monde à des années lumières du mien, mais je ne m’explique toujours pas leur drôle de comportement, leur discours sur l’amitié authentique, puis la demande d’argent… et je n’ai aucune idée de la vision qu’ils ont de la femme européenne, si ce n’est qu’elle est très loin de la réalité et pas très respectueuse ou innocente.</p>

        <p>C’est aussi à Varanasi que j’ai dégusté le meilleur lassi d’Inde, et pour cette unique raison c’est une ville qui vaut toute mon estime. J’en chéris également tendrement le souvenir car malgré tout j’ai adoré l’atmosphère là-bas, la sensibilité du tableau, beau et doux, léger et profond. Les milliers de cerfs-volants libérés dans le ciel pastel à la tombée de la nuit, l’orbe de feu qui explosent une dernière fois avant de céder à la litanie de l’appel à la prière des mosquées, le Gange, les singes, la nourriture, l’agitation inouïe, comme une fête éternelle et confuse. Le festival surtout m’a marqué, c’était vraiment un moment magique. Ils ont illuminé les ghâts avec des milliards de bougies fait main, fabriquées par chaque habitant de la ville, lancés de nombreux feux d’artifices, ramotés les plus grands prêtres et gurus de l’Inde qui faisaient des sermons passionnés dans des micros grésillant, des danseuses, des stars, des hommes politiques. C’était vraiment de la folie, toute la ville était décorée et brillait de mille feux. J’ai eu la chance de le vivre depuis le Gange sur une barque où je ne perdais pas une miette du spectacle, entourée des bougies et fleurs soufflées sur les flots comme des bouteilles à la mer d’expiation, veillée par une lune énorme et rouge qui laissait une trace sanglante et féerique dans les eaux noires.</p>

        <p>Ah et j’allais oublier ! C’est aussi là que j’ai reçu ma première demande en mariage. C’était simultanée à ma première fois dans une gare indienne. Quelle expérience… La gare où je prenais mon train (pas exactement à Varanasi) était particulièrement grouillante et brouillonne. J’ai donc débarqué là sans aucun repère, vite débordée par la marée humaine, le manque d’information, la voix sncf qui s’était lancée dans un concerto pour trompette, la vache grise sur les rails… alors j’ai fait ce que tout européen normal aurait fait : j’ai demandé au premier venu. Erreur basique en Asie. La règle d’or est bien de ne jamais rien demandé à la population locale. Ils sont plein de bonne volonté mais complètement incompétents, et le pire est qu’ils préfèrent être écrasés sur place par un samosa géant que d’avouer leur ignorance. Ça se finit donc par une perte de temps inouïe (car ils sont aussi bornés qu’inutiles) et/ou dans le pire des cas, de fausses indications qui entraînent la perte d’orientation rapide et le coup de grâce final. Ou bien… une demande en mariage ! Logique. Voici le déroulement des faits : <br />

        Me voici donc, jeune blanche en détresse, à demander mon chemin au premier venu, quadragénaire indien aux lèvres délicatement rosées par le pâan. L’individu ne parlant pas un mot d’anglais, il compare les tickets et me fait comprendre qu’on prend le même train et qu’on est dans le même compartiment, il faut donc que je reste à ses côtés. Il commence alors à me raconter sa vie, en hindi naturellement, puis en vient à un interrogatoire qui éveille ma suspicion. Il me questionne dans un anglais bancal sur ma situation civile, ma famille, notamment très curieux à propos de mon frère et mon père (où sont-ils? Que font-ils?), puis en vient à me demander mon numéro français (WhatsApp number, tous les indiens vous le demanderont plus ou moins lourdement), et encore une fois cette rengaine sur l’amitié, voulant savoir à quel point je l’aimais (en anglais « to like » plutôt que « love ») après ce riche et généreux partage. </p>

        <p>Ma réaction ? Exploser de rire, chercher des yeux la caméra cachée. Puis vient le train qui débarque dans un vacarme de tous les diables et la course folle avec et contre tous pour trouver le bon compartiment. C’est dans ce moment particulièrement stressant (essayez de courir parmi une centaine de personnes en panique quand vous vous trimballez un âne mort de 15 kilos sur le dos et un bébé âne mort de 5 kilos sur le ventre) que l’énergumène, qui tenait énergiquement ma main, ou plutôt qui tentait de me désosser le bras, jugea bon de se retourner et de me crier « would you marry me ? ». <br/>

        Ma réaction : la même que quand on me demande si je mange mes frites avec de la mayonnaise : hurler de toutes mes forces « NO » sans aucune hésitation. <br/>

        Le pauvre était tout déçu, il m’apporta à manger tout le long du trajet en me demandant de reconsidérer et de rencontrer ses parents qui étaient également dans le compartiment. Quand je dis « le long du trajet », je veux dire 40h. Oui, je partais pour Chennai, au Sud Est de l’Inde, que j’allais atteindre après deux jours de train.</p>
      </div>
      <div className="weather">
        <iframe src="https://www.accuweather.com/en/in/varanasi/206681/current-weather/206681"></iframe>
      </div>
      <div className="Money_converter">
        <iframe src="https://www.xe.com/currencyconverter/"></iframe>
      </div>

      <hr />
      <a href="/" className="menu">Plus d'articles: </a>
      <div className="more_article">
        <Page />
      </div>
    </div>
  )
}

export default Varanasi;
